// Re-export all shared constants
export {
  PRE_CONFIGURED_GAS_URL,
  STORAGE_KEY_DATA,
  STORAGE_KEY_SETTINGS,
  STORAGE_KEY_SESSION,
  STORAGE_KEY_LOCATIONS,
  STORAGE_KEY_QUEUE,
  STORAGE_KEY_ONBOARDING,
  STORAGE_KEY_LANG,
  DEFAULT_BATTERY_CAPACITY,
  DEFAULT_ELECTRICITY_RATE,
  DEFAULT_NIGHT_RATE,
  MAX_CHARGE_HOURS,
  VEHICLE_PRESETS,
  CSV_HEADERS,
} from "../../shared/constants/defaults.ts";
